### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by friendlyanon**
I didn't touch the tests because those could use lots of modifications, which is outside the scope of this PR.  
After the test files are cleaned up, I can make a new PR for adding them to CMake.

### CODE REVIEW

**Comment by jk-jeon** [comment]
Wow, thanks so much!

**Comment by friendlyanon** [comment]
After the tests have been adjusted, please tag me with a @mention, so I can add them to the CMake files.

**Comment by jk-jeon** [comment]
@friendlyanon 

I modified all test/benchmark files. With the additional include directory (`test/include`), I expect all should work now.

**Comment by expnkx** [comment]
any new parsing algorithm based on the dragon box?

**Comment by friendlyanon** [comment]
@jk-jeon ah, I meant a more comprehensive set of changes.  
You should have separate .cpp files for each test so it can be compiled and added separately in the test CMakeLists file.

I don't really understand what's going on in the `benchmark` folder either.

I think I will just open an issue to track this.

**Comment by jk-jeon** [comment]
@friendlyanon  Aha. Thanks so much for all of these. I'll try to make changes as you suggested.

@expnkx First, why are you asking that in this completely unrelated PR? Second, the answer is no. The inverse conversion (decimal-to-binary) does not involve iterative search, so there are not so much room for creativity compared to binary-to-decimal case. I made a separate repo for more comprehensive floating-point conversion library [here](https://github.com/jk-jeon/fp), so please make an issue there if you want to ask/suggest me anything about parsing.

**Pull request merged**
